insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (154, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (169, 'Classe II', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (180, 'Classe I', 'PAT');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (116, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (117, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (100,  'Destinato alla trasformazione', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (155, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (173, 'Destinato alla trasformazione', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (167, 'Classe II', 'DOP');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (153, 'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (178, 'Classe II', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (131, 'Classe I', 'Biologico');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (132, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (135, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (119, 'Classe II', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (103, 'Classe Extra', 'SQNPI');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (105, 'Classe Extra', 'STG');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (104, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (161, 'Classe II', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (101,  'Destinato alla trasformazione', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (102,  'Destinato alla trasformazione', 'DOP');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (147, 'Classe I', 'STG');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (159, 'Classe II', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (99, 'Classe II', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (170, 'Classe II', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (111,  'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (130,  'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (157, 'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (112, 'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (168, 'Destinato alla trasformazione', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (148, 'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (163, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (165, 'Classe Extra', 'STG');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (172, 'Classe II', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (177,  'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (174, 'Destinato alla trasformazione', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (142, 'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (122, 'Classe II', 'STG');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (164, 'Destinato alla trasformazione', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (140, 'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (139, 'Classe Extra', 'DOP');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (138, 'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (151, 'Destinato alla trasformazione', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (113, 'Destinato alla trasformazione', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (114, 'Destinato alla trasformazione', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (106, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (108, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (109, 'Classe II', 'Biologico');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (107, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (152, 'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (118, 'Classe II', 'IGP');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (166, 'Classe Extra', 'Biologico');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (171, 'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (160, 'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (115, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (156, 'Destinato alla trasformazione', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (125, 'Classe II', 'Biologico');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (121, 'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (158, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (110, 'Destinato alla trasformazione', 'SQNPI');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (150, 'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (175, 'Destinato alla trasformazione', 'IGP');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (144, 'Classe II', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (123, 'Destinato alla trasformazione', 'SQNPI');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (124, 'Classe I', 'STG');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (162, 'Classe II', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (145, 'Destinato alla trasformazione', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (146, 'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (179, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (143, 'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (120, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (176, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (137, 'Classe Extra', 'DOP');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (136, 'Classe I', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (126, 'Destinato alla trasformazione', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (127, 'Classe I', 'SQNPI');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (128, 'Destinato alla trasformazione', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (129, 'Destinato alla trasformazione', 'IGP');
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (134, 'Classe Extra', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (133, 'Destinato alla trasformazione', NULL);
insert into agricolo (id_prodotto, categoria_commerciale, certificazione) values (149,  'Classe Extra', 'Biologico');