insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (190, 'Equino', 'Sella Italiano', 122, 'Malato', '2026-01-13');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (215, 'Suino', 'Landrace', 22, 'Buono', '2026-02-27');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (229, 'Caprino', 'Camosciata delle Alpi', 109, 'Ferito lieve', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (269, 'Suino', 'Duroc', 52, 'Sotto osservazione', '2026-01-05');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (275, 'Avicolo', 'Sussex', 61, 'Ottimo', '2026-02-03');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (292, 'Ovino', 'Suffolk', 32, 'In cura', '2025-12-21');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (41, 'Avicolo', 'Plymouth Rock', 6, 'Buono', '2026-04-09');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (64, 'Caprino', 'Maltese', 79, 'In recupero', '2026-04-26');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (135, 'Caprino', 'Maltese', 38, 'Ferito lieve', '2026-04-12');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (142, 'Bufalino', 'Mediterraneo Italiano', 129, 'In cura', '2026-02-19');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (166, 'Cunicolo', 'Nero', 44, 'Ottimo', '2026-01-10');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (174, 'Equino', 'Quarter Horse', 97, null, '2026-01-12');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (176, 'Ovino', 'Appenninica', 75, 'Discreto', '2026-03-27');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (196, 'Ovino', 'Sarda', 121, 'Buono', '2026-01-09');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (207, 'Avicolo', 'Isa Brown', 134, 'Malato', '2026-01-28');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (245, 'Ovino', 'Sarda', 135, 'Sotto osservazione', '2026-01-28');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (274, 'Bovino', 'Chianina', 140, 'Malato', '2026-04-27');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (297, 'Caprino', 'Nubiana', 22, 'Discreto', '2026-04-19');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (13, 'Avicolo', 'Livornese', 44, 'In recupero', '2026-01-16');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (33, 'Ovino', 'Suffolk', 45, 'Malato', '2026-02-25');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (49, 'Bovino', 'Charolaise', 125, 'Ottimo', '2026-01-28');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (57, 'Suino', 'Landrace', 89, 'Ferito lieve', '2026-01-19');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (65, 'Equino', 'Maremmano', 38, 'Ferito lieve', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (70, 'Suino', 'Duroc', 59, 'Ottimo', '2026-03-27');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (77, 'Suino', 'Landrace', 65, 'Buono', '2026-03-17');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (80, 'Bovino', 'Frisona', 136, 'Sotto osservazione', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (95, 'Avicolo', 'Plymouth Rock', 137, 'Discreto', '2025-12-06');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (107, 'Bovino', 'Bruna Alpina', 102, 'Sotto osservazione', '2026-02-09');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (114, 'Cunicolo', 'Bianco di Nuova Zelanda', 94, 'Ferito lieve', '2026-03-30');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (140, 'Cunicolo', 'Nero', 59, 'In recupero', '2025-12-05');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (158, 'Suino', 'Pietrain', 90, 'Critico', '2026-04-04');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (189, 'Cunicolo', 'Bianco di Nuova Zelanda', 20, 'In recupero', '2026-03-22');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (206, 'Ovino', 'Suffolk', 51, 'Buono', '2026-04-25');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (235, 'Suino', 'Duroc', 150, 'Malato', '2025-12-16');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (244, 'Avicolo', 'Plymouth Rock', 114, 'Ferito lieve', '2026-04-07');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (296, 'Bovino', 'Bruna Alpina', 37, 'Sotto osservazione', '2025-12-01');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (31, 'Avicolo', 'Ross', 25, 'Discreto', '2026-04-02');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (40, 'Equino', 'Maremmano', 129, 'Discreto', '2026-04-24');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (93, 'Ovino', 'Bergamasca', 50, 'Discreto', '2026-03-22');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (204, 'Suino', 'Landrace', 62, 'Malato', '2026-02-25');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (270, 'Caprino', 'Nubiana', 109, 'Critico', '2026-03-14');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (281, 'Equino', 'Quarter Horse', 64, 'In recupero', '2026-04-07');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (285, 'Suino', 'Nero Siciliano', 27, 'Discreto', '2026-02-02');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (291, 'Suino', 'Duroc', 36, 'In recupero', '2026-01-05');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (18, 'Caprino', 'Maltese', 42, 'Buono', '2026-01-27');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (58, 'Cunicolo', 'Nero', 59, 'Ottimo', '2026-02-01');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (69, 'Bovino', 'Bruna Alpina', 84, 'Sotto osservazione', '2026-03-18');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (94, 'Bovino', 'Pezzata Rossa', 70, 'Discreto', '2025-12-05');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (109, 'Equino', 'Haflinger', 137, 'Sotto osservazione', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (181, 'Bovino', 'Charolaise', 75, 'Ferito lieve', '2026-04-21');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (203, 'Bufalino', 'Mediterraneo Italiano', 52, 'Buono', '2026-01-04');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (205, 'Bovino', 'Bruna Alpina', 56, 'In recupero', '2026-03-02');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (240, 'Cunicolo', 'Nero', 64, null, '2026-04-12');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (278, 'Suino', 'Landrace', 51, 'Sotto osservazione', '2026-04-05');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (298, 'Ovino', 'Sarda', 14, 'Ottimo', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (149, 'Avicolo', 'Sussex', 102, 'In cura', '2025-12-12');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (168, 'Ovino', 'Appenninica', 83, 'In cura', '2026-02-27');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (211, 'Avicolo', 'Livornese', 107, 'Malato', '2026-03-11');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (212, 'Equino', 'Sella Italiano', 22, 'In recupero', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (222, 'Avicolo', 'Livornese', 2, 'Sotto osservazione', '2026-03-24');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (287, 'Avicolo', 'Sussex', 104, 'Sano', '2026-04-29');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (34, 'Caprino', 'Nubiana', 9, null, null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (68, 'Equino', 'Sella Italiano', 18, 'Sotto osservazione', '2026-03-30');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (76, 'Avicolo', 'Isa Brown', 145, 'Sotto osservazione', '2026-02-12');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (92, 'Caprino', 'Maltese', 25, 'Sano', '2026-02-15');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (127, 'Equino', 'Maremmano', 10, 'Ottimo', '2025-12-22');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (138, 'Bufalino', 'Mediterraneo Italiano', 61, 'Sano', '2026-04-21');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (173, 'Ovino', 'Sarda', 66, 'Buono', '2025-12-12');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (177, 'Caprino', 'Saanen', 118, 'Buono', '2026-02-28');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (180, 'Cunicolo', 'Gigante Fiammingo', 86, 'Critico', '2026-02-14');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (280, 'Caprino', 'Maltese', 124, 'Sotto osservazione', '2026-03-11');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (289, 'Equino', 'Quarter Horse', 7, 'Buono', '2026-01-02');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (22, 'Caprino', 'Maltese', 12, 'Ferito lieve', '2026-04-27');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (23, 'Caprino', 'Nubiana', 74, 'Sano', '2026-01-28');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (78, 'Caprino', 'Maltese', 30, 'Malato', '2026-03-24');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (116, 'Caprino', 'Saanen', 8, 'In recupero', '2026-04-06');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (130, 'Bovino', 'Bruna Alpina', 119, 'In cura', '2026-02-03');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (178, 'Ovino', 'Sarda', 36, 'Discreto', '2026-02-13');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (182, 'Ovino', 'Comisana', 97, null, '2026-03-07');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (184, 'Bufalino', 'Mediterraneo Italiano', 82, 'Sotto osservazione', '2026-01-31');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (192, 'Caprino', 'Saanen', 25, 'Critico', '2025-12-04');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (238, 'Bufalino', 'Mediterraneo Italiano', 133, 'Critico', '2026-03-02');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (259, 'Bovino', 'Pezzata Rossa', 76, 'Sano', '2026-03-23');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (276, 'Bovino', 'Limousine', 67, 'Critico', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (50, 'Ovino', 'Suffolk', 51, 'In recupero', '2026-04-12');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (91, 'Bovino', 'Limousine', 23, 'Buono', '2025-12-23');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (98, 'Bufalino', 'Mediterraneo Italiano', 85, 'In cura', '2026-04-12');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (125, 'Bovino', 'Chianina', 60, 'Malato', '2026-04-05');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (128, 'Suino', 'Nero Siciliano', 94, 'Sano', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (132, 'Cunicolo', 'Bianco di Nuova Zelanda', 72, 'Buono', '2026-02-23');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (148, 'Ovino', 'Sarda', 117, 'Ottimo', '2026-03-14');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (167, 'Bufalino', 'Mediterraneo Italiano', 136, 'Discreto', '2026-02-09');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (209, 'Bufalino', 'Mediterraneo Italiano', 97, 'In recupero', '2026-02-01');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (246, 'Bovino', 'Bruna Alpina', 114, 'Ferito lieve', '2025-12-26');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (248, 'Equino', 'Quarter Horse', 44, 'Ottimo', '2026-03-11');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (264, 'Bufalino', 'Mediterraneo Italiano', 102, 'Ottimo', '2025-12-31');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (266, 'Suino', 'Pietrain', 3, 'Sano', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (271, 'Ovino', 'Sarda', 92, 'Ottimo', '2026-01-20');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (293, 'Ovino', 'Appenninica', 40, 'Malato', '2025-12-28');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (1, 'Ovino', 'Bergamasca', 49, 'In recupero', '2026-01-29');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (6, 'Ovino', 'Appenninica', 140, 'Sotto osservazione', '2026-02-06');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (27, 'Ovino', 'Sarda', 115, 'Discreto', '2026-01-09');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (36, 'Bovino', 'Limousine', 68, 'In cura', '2026-01-03');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (52, 'Caprino', 'Saanen', 10, 'In recupero', '2026-01-29');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (56, 'Avicolo', 'Livornese', 89, 'Ottimo', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (101, 'Caprino', 'Saanen', 127, 'Buono', '2026-01-19');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (154, 'Bovino', 'Pezzata Rossa', 104, 'Ottimo', '2026-02-25');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (188, 'Equino', 'Haflinger', 25, null, '2026-01-24');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (195, 'Suino', 'Pietrain', 21, 'Ferito lieve', '2026-04-05');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (210, 'Ovino', 'Sarda', 135, 'Ottimo', '2026-02-07');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (267, 'Bovino', 'Frisona', 116, 'Discreto', '2026-04-23');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (283, 'Ovino', 'Bergamasca', 47, 'Discreto', '2026-04-28');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (294, 'Avicolo', 'Plymouth Rock', 86, 'Buono', '2026-02-01');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (2, 'Ovino', 'Bergamasca', 68, 'Buono', '2026-04-19');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (4, 'Equino', 'Haflinger', 89, 'Critico', '2026-02-26');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (11, 'Bufalino', 'Mediterraneo Italiano', 80, 'In recupero', '2026-02-06');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (16, 'Bovino', 'Charolaise', 70, 'In recupero', '2026-03-25');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (26, 'Suino', 'Large White', 9, 'Critico', '2026-03-07');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (30, 'Bufalino', 'Mediterraneo Italiano', 112, 'Malato', '2026-02-16');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (53, 'Avicolo', 'Livornese', 21, 'In cura', '2026-01-10');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (105, 'Ovino', 'Comisana', 97, 'Ferito lieve', '2026-03-28');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (110, 'Suino', 'Landrace', 110, 'Ferito lieve', '2025-12-12');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (146, 'Avicolo', 'Plymouth Rock', 115, 'In cura', '2026-04-05');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (172, 'Bufalino', 'Mediterraneo Italiano', 76, 'Critico', '2026-04-17');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (194, 'Bovino', 'Pezzata Rossa', 123, 'Ferito lieve', '2026-03-05');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (202, 'Bufalino', 'Mediterraneo Italiano', 140, 'Critico', '2025-12-27');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (221, 'Avicolo', 'Plymouth Rock', 76, 'Critico', '2025-12-03');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (227, 'Suino', 'Pietrain', 146, 'Sano', '2026-01-11');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (233, 'Ovino', 'Bergamasca', 4, 'Critico', '2026-01-07');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (239, 'Ovino', 'Appenninica', 88, 'In cura', '2026-03-11');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (258, 'Ovino', 'Comisana', 36, 'Buono', '2026-03-31');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (284, 'Cunicolo', 'Bianco di Nuova Zelanda', 3, 'Sano', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (288, 'Bufalino', 'Mediterraneo Italiano', 110, 'Ferito lieve', '2026-01-05');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (124, 'Cunicolo', 'Bianco di Nuova Zelanda', 79, 'Ferito lieve', '2026-01-02');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (144, 'Equino', 'Sella Italiano', 3, 'Malato', '2026-02-05');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (152, 'Ovino', 'Sarda', 124, 'Critico', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (155, 'Bovino', 'Pezzata Rossa', 53, 'In recupero', '2026-01-01');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (156, 'Cunicolo', 'Nero', 28, null, '2026-02-24');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (162, 'Equino', 'Maremmano', 121, 'In recupero', '2026-03-26');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (171, 'Caprino', 'Camosciata delle Alpi', 73, null, '2026-04-05');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (199, 'Cunicolo', 'Nero', 136, 'Ferito lieve', '2026-04-17');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (232, 'Ovino', 'Suffolk', 145, 'Critico', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (241, 'Avicolo', 'Ross', 75, 'In recupero', '2026-02-05');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (243, 'Caprino', 'Nubiana', 23, 'Malato', '2025-12-23');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (254, 'Bufalino', 'Mediterraneo Italiano', 52, 'Buono', '2026-02-14');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (260, 'Avicolo', 'Sussex', 12, 'Critico', '2026-02-07');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (15, 'Equino', 'Haflinger', 54, 'Sotto osservazione', '2026-04-15');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (66, 'Avicolo', 'Isa Brown', 50, 'Critico', '2026-02-25');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (72, 'Bufalino', 'Mediterraneo Italiano', 52, 'Critico', '2026-01-16');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (79, 'Suino', 'Large White', 129, null, '2026-04-29');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (84, 'Bufalino', 'Mediterraneo Italiano', 22, 'Ottimo', '2026-03-03');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (89, 'Avicolo', 'Plymouth Rock', 12, 'Ferito lieve', '2026-03-28');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (111, 'Avicolo', 'Ross', 14, 'Malato', '2026-03-15');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (115, 'Cunicolo', 'Gigante Fiammingo', 91, 'Sotto osservazione', '2026-01-07');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (201, 'Ovino', 'Suffolk', 36, 'Discreto', '2026-04-14');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (216, 'Cunicolo', 'Bianco di Nuova Zelanda', 1, 'Malato', '2026-02-20');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (218, 'Cunicolo', 'Nero', 124, 'Ottimo', '2026-04-02');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (219, 'Suino', 'Nero Siciliano', 68, 'Critico', '2025-12-27');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (225, 'Equino', 'Sella Italiano', 7, 'In cura', '2026-02-07');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (251, 'Cunicolo', 'Gigante Fiammingo', 110, 'Ottimo', '2026-04-30');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (262, 'Avicolo', 'Plymouth Rock', 75, 'Sano', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (286, 'Avicolo', 'Sussex', 67, 'Sano', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (300, 'Cunicolo', 'Gigante Fiammingo', 60, 'In cura', '2026-03-07');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (10, 'Bovino', 'Chianina', 100, 'Sano', '2026-01-09');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (32, 'Cunicolo', 'Bianco di Nuova Zelanda', 25, 'Sotto osservazione', '2026-04-16');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (54, 'Bovino', 'Frisona', 39, 'Ferito lieve', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (82, 'Equino', 'Haflinger', 71, 'Discreto', '2025-12-02');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (90, 'Suino', 'Large White', 16, 'Malato', '2026-02-08');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (100, 'Equino', 'Quarter Horse', 131, 'Ottimo', '2026-03-02');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (102, 'Ovino', 'Appenninica', 109, 'In cura', '2026-04-12');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (117, 'Caprino', 'Nubiana', 46, null, '2026-04-25');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (120, 'Equino', 'Sella Italiano', 33, 'Discreto', '2026-01-10');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (131, 'Suino', 'Pietrain', 104, 'Ferito lieve', '2026-04-07');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (151, 'Equino', 'Sella Italiano', 133, 'Sotto osservazione', null);
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (157, 'Bufalino', 'Mediterraneo Italiano', 108, null, '2026-02-25');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (249, 'Caprino', 'Nubiana', 126, 'Ferito lieve', '2026-01-23');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (257, 'Suino', 'Large White', 125, 'Sano', '2026-04-02');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (263, 'Bufalino', 'Mediterraneo Italiano', 62, 'Malato', '2026-01-26');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (265, 'Avicolo', 'Sussex', 11, 'In recupero', '2026-01-29');
insert into bestiame (id_attivita, specie, razza, numero_capi, stato_salute, data_ultimo_controllo) values (299, 'Caprino', 'Nubiana', 60, null, '2026-02-24');