insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (45, 'UHT', 'Omogeneizzazione');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (97, 'Surgelato', 'Affumicatura con legno di faggio');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (65, 'Surgelato', 'Affumicatura con legno di faggio');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (75, 'Surgelato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (74, 'UHT', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (5, 'Stagionato', 'Affumicatura con legno di faggio');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (6, 'Surgelato', 'Scrematura meccanica');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (39, 'Fresco', 'Scrematura meccanica');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (51, 'UHT', 'Affumicatura con legno di faggio');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (47, 'Stagionato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (50, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (55, 'Surgelato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (67, 'UHT', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (53, 'Essiccato', 'Scrematura meccanica');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (52, 'UHT', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (54, 'Stagionato', 'Affumicatura con legno di faggio');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (49, 'Surgelato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (56, 'UHT', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (48, 'Essiccato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (80, 'UHT', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (85, 'Essiccato', 'Omogeneizzazione');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (84, 'Surgelato', 'Affumicatura con legno di faggio');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (86, 'Fresco', 'Affumicatura con legno di faggio');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (88, 'Essiccato', 'Salatura a secco');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (87, 'Essiccato', 'Affumicatura con legno di faggio');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (12, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (26, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (28, 'Stagionato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (31, 'Surgelato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (29, 'Surgelato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (30, 'Fresco', 'Pastorizzazione HTST');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (27, 'UHT', 'Affumicatura con legno di faggio');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (32, 'Fresco', 'Salatura a secco');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (33, 'Stagionato', 'Omogeneizzazione');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (35, 'Fresco', 'Pastorizzazione HTST');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (25, 'Fresco', 'Salatura a secco');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (22, 'Essiccato', 'Termizzazione');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (83, 'Stagionato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (36, 'Fresco', 'Pastorizzazione HTST');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (24, 'UHT', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (34, 'Surgelato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (23, 'Stagionato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (90, 'Stagionato', 'Termizzazione');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (92, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (68, 'UHT', 'Omogeneizzazione');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (70, 'Essiccato', 'Omogeneizzazione');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (69, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (66, 'UHT', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (94, 'UHT', 'Affumicatura con legno di faggio');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (96, 'Stagionato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (95, 'Surgelato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (1, 'Stagionato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (3, 'Essiccato', 'Stagionatura in grotta');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (81, 'Essiccato', 'Salatura a secco');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (2, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (4, 'UHT', 'Scrematura meccanica');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (77, 'Stagionato', 'Affumicatura con legno di faggio');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (79, 'Surgelato', 'Affumicatura con legno di faggio');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (78, 'Essiccato', 'Omogeneizzazione');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (20, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (21, 'UHT', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (63, 'Essiccato', 'Pastorizzazione HTST');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (8, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (7, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (37, 'UHT', 'Stagionatura in grotta');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (38, 'Surgelato', 'Salatura a secco');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (71, 'Surgelato', 'Stagionatura in grotta');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (72, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (73, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (62, 'Stagionato', 'Scrematura meccanica');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (61, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (98, 'Essiccato', 'Omogeneizzazione');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (40, 'UHT', 'Salatura a secco');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (41, 'Surgelato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (19, 'Surgelato', 'Omogeneizzazione');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (18, 'UHT', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (16, 'Surgelato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (17, 'Fresco', 'Affumicatura con legno di faggio');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (59, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (60, 'Surgelato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (11, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (57, 'Stagionato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (58, 'Essiccato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (42, 'Surgelato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (82, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (14, 'Fresco', 'Scrematura meccanica');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (64, 'Stagionato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (46, 'Essiccato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (43, 'Surgelato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (44, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (93, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (141, 'UHT', 'Pastorizzazione HTST');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (91, 'Surgelato', 'Scrematura meccanica');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (10, 'Stagionato', 'Stagionatura in grotta');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (13, 'Fresco', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (9, 'Fresco', 'Salatura a secco');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (15, 'Essiccato', 'Pastorizzazione HTST');
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (89, 'Surgelato', NULL);
insert into derivato_animale (id_prodotto, tipologia_conservazione, trattamenti_subiti) values (76, 'Essiccato', NULL);