INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Terriccio', 1016.83, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Mangime bovini svezzamento', 12863.51, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Vasetti vetro', 604, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Mangime pollame', 5064.45, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Rete antigrandine', 647.05, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Correttori di pH', 632.94, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Disinfettante stalle', 232.73, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Acqua', 618.26, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Cassette legno', 1202, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Etichette adesive', 1218, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Tappi vasetti', 408, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'tipo_risorsa', 410.74, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Mangime bovini ingrasso', 2359.13, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Semi foraggio', 949.78, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Olio motore agricolo', 734.92, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Sale pastorizio', 1359.95, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Compost', 2859.62, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Olio motore agricolo', 470.48, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Semi cereali', 373.04, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Mangime bovini ingrasso', 4017.83, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Film plastico serre', 813.21, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Fieno misto', 3029.45, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Terriccio', 832.13, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Paglia di grano', 16580.09, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Olio motore agricolo', 985.77, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Sale pastorizio', 1103.67, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'tipo_risorsa', 751.51, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Compost', 568.68, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Rete antigrandine', 746.1, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Mangime bovini ingrasso', 12367, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Farmaci veterinari base', 497.27, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Integratori alimentari animali', 1234.24, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Fieno misto', 11913.0, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Insetticida', 47.61, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Tubi per irrigazione', 138.71, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Sacchi per raccolta', 100, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Etichette adesive', 968, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Mangime bovini svezzamento', 10328.54, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Semi foraggio', 245.5, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Fieno misto', 3674.15, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Farmaci veterinari base', 1376.82, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Sale pastorizio', 938.72, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Semi cereali', 176.32, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Fertilizzante', 1104.15, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Tappi vasetti', 3, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Acqua', 521.85, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Sacchi per raccolta', 613, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Correttori di pH', 1379.05, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Olio motore agricolo', 895.86, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Bancali (pallet)', 619, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Mangime pollame', 10558.07, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Semi ortaggi', 60.96, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Bancali (pallet)', 1295, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Film plastico serre', 151.29, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Rete antigrandine', 956.2, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Tappi vasetti', 498, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Semi cereali', 137.57, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'tipo_risorsa', 867.73, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Correttori di pH', 1006.87, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Semi foraggio', 690.07, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Tubi per irrigazione', 310.5, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Rete antigrandine', 436.24, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Erbicida diserbante', 481.06, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Urea agricola', 355.46, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Mangime bovini ingrasso', 7563.59, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Olio motore agricolo', 1326.56, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Sacchi per raccolta', 754, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Sacchi per raccolta', 224, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Semi ortaggi', 892.28, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Vasetti vetro', 638, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Integratori alimentari animali', 1043.25, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Mangime pollame', 2467.88, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Cassette legno', 1347, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Acqua', 913.31, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Corda imballaggio', 554.36, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Semi foraggio', 802.57, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Mangime bovini svezzamento', 2152.07, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Vasetti vetro', 263, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Semi foraggio', 508, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Film plastico serre', 557.34, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Etichette adesive', 961, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Vasetti vetro', 430, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Fieno erba medica', 589.82, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Fieno erba medica', 6820.03, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Disinfettante stalle', 373, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Semi foraggio', 776.31, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Compost', 1572.48, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Rete antigrandine', 1067.08, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Corda imballaggio', 998.68, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Paglia di grano', 8807.95, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Insetticida', 515.76, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Sacchi per raccolta', 1225, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Olio motore agricolo', 351.82, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Vasetti vetro', 737, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Fertilizzante', 946.82, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Insetticida', 907.81, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Disinfettante stalle', 1212.22, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Rete antigrandine', 424.56, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Lampade agricole', 364, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Correttori di pH', 11.07, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Urea agricola', 1002, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Sale pastorizio', 149.93, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Sacchi per raccolta', 454, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Fieno erba medica', 6427.8, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Tubi per irrigazione', 417.7, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Fertilizzante', 573.42, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Cassette plastica', 357, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Correttori di pH', 945.04, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Mangime bovini svezzamento', 2948.45, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Mangime pollame', 1706.16, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Mangime bovini svezzamento', 11532.73, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Tappi vasetti', 394, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Fieno erba medica', 8143.71, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Sale pastorizio', 24, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Mangime bovini svezzamento', 6142.97, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Semi cereali', 642, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Acqua', 913.55, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Erbicida diserbante', 278.65, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Urea agricola', 257, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Farmaci veterinari base', 197.75, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Correttori di pH', 198.63, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Vasetti vetro', 674, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Fertilizzante', 1293.94, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Lampade agricole', 919, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Semi cereali', 710.41, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Fieno erba medica', 3091.78, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Tappi vasetti', 556, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Bancali (pallet)', 1138, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Sacchi per raccolta', 715, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Urea agricola', 1184.55, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Cassette plastica', 588, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'tipo_risorsa', 755.79, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Paglia di grano', 529.34, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Fieno erba medica', 3417, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Erbicida diserbante', 502.18, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Compost', 680.16, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Olio motore agricolo', 1108.35, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Fertilizzante', 680.54, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Mangime pollame', 3216.95, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Sale pastorizio', 12.02, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Etichette adesive', 745, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Mangime bovini svezzamento', 13204.89, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Mangime bovini ingrasso', 4613, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Acqua', 1103.53, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Semi foraggio', 912.4, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Film plastico serre', 624.51, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Sacchi per raccolta', 882, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Fieno erba medica', 3851.75, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Cassette legno', 820, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Sale pastorizio', 1178, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Sale pastorizio', 1044.78, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Lampade agricole', 454, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Bancali (pallet)', 349, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Cassette legno', 828, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Tubi per irrigazione', 37.08, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Fertilizzante', 1360.68, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Lampade agricole', 240, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Insetticida', 1270.07, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Film plastico serre', 228.68, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Semi cereali', 736.19, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Erbicida diserbante', 1320.34, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Terriccio', 476.76, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Cassette plastica', 767, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Sacchi per raccolta', 880, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Integratori alimentari animali', 1364.79, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Rete antigrandine', 58.82, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Fertilizzante', 1052.44, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Rete antigrandine', 361.96, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Terriccio', 164.82, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Gasolio agricolo', 988.41, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Terriccio', 679.47, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'tipo_risorsa', 583.7, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Fieno erba medica', 11613.66, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Olio motore agricolo', 1137.78, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Semi ortaggi', 373.84, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Mangime bovini svezzamento', 4165.53, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Cassette plastica', 786, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Integratori alimentari animali', 1011.5, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Etichette adesive', 544, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Vasetti vetro', 1303, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Cassette plastica', 64, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Tubi per irrigazione', 384, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Sale pastorizio', 381.78, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Compost', 8491.18, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Acqua', 733.75, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Farmaci veterinari base', 1147.24, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Vasetti vetro', 341, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Olio motore agricolo', 350.57, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Farmaci veterinari base', 1065.08, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Erbicida diserbante', 665.2, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Corda imballaggio', 1185.83, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Paglia di grano', 4913.74, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Mangime bovini ingrasso', 12093, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Etichette adesive', 1087, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Disinfettante stalle', 666.92, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Integratori alimentari animali', 516.37, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Bancali (pallet)', 769, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Semi cereali', 599.86, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Mangime pollame', 12270.4, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Gasolio agricolo', 681.31, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Correttori di pH', 1063.89, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Fieno misto', 1675.89, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Rete antigrandine', 264.18, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Fieno misto', 928.2, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Olio motore agricolo', 44.58, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Fieno erba medica', 12367.55, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Cassette plastica', 1330, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Film plastico serre', 312.22, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Urea agricola', 874.97, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Urea agricola', 841, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Fertilizzante', 62.45, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Farmaci veterinari base', 727.81, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Mangime pollame', 4608.79, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Mangime pollame', 9452.07, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Corda imballaggio', 761.85, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Erbicida diserbante', 1012.69, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Etichette adesive', 415, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Cassette legno', 734, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Semi foraggio', 170.76, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Rete antigrandine', 412, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Sale pastorizio', 554.56, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Tappi vasetti', 282, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Sacchi per raccolta', 443, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Rete antigrandine', 836.2, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Erbicida diserbante', 460.77, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Disinfettante stalle', 224.99, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Mangime pollame', 10920.39, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Semi cereali', 1286.46, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Semi cereali', 226.76, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Terriccio', 1311.94, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Erbicida diserbante', 966.92, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Paglia di grano', 12403.5, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Disinfettante stalle', 751.13, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Fertilizzante', 634.46, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'tipo_risorsa', 1356, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Olio motore agricolo', 165.31, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Tubi per irrigazione', 603, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Cassette legno', 819, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Disinfettante stalle', 764.9, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Rete antigrandine', 1174.19, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Mangime pollame', 6601.47, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Gasolio agricolo', 320.95, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Bancali (pallet)', 714, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Paglia di grano', 476.89, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Disinfettante stalle', 952.42, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Rete antigrandine', 944.61, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Tappi vasetti', 781, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Semi foraggio', 363.4, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Cassette plastica', 400, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Fertilizzante', 1163.8, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Rete antigrandine', 1330.52, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Film plastico serre', 177.57, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Integratori alimentari animali', 1391.96, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Lampade agricole', 13, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Etichette adesive', 1246, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Semi ortaggi', 713.15, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Cassette plastica', 1319, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Bancali (pallet)', 1364, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Mangime bovini svezzamento', 11484.63, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Fieno misto', 12271.33, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Mangime pollame', 9370.34, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Cassette legno', 508, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Correttori di pH', 459.76, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Semi foraggio', 89.54, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Mangime bovini svezzamento', 10284.12, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Correttori di pH', 1263.12, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Fieno erba medica', 13294.11, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Mangime bovini svezzamento', 13678.26, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Fieno misto', 591.31, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Integratori alimentari animali', 1132.97, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Insetticida', 1094.64, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Sale pastorizio', 1306.86, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Bancali (pallet)', 355, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Vasetti vetro', 591, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Urea agricola', 735.3, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Film plastico serre', 525.27, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Tappi vasetti', 1300, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Semi ortaggi', 457.29, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Vasetti vetro', 883, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Vasetti vetro', 963, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Paglia di grano', 2579.97, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Compost', 749.77, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Cassette plastica', 1029, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Acqua', 1154, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Insetticida', 55.84, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Disinfettante stalle', 1370.96, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Bancali (pallet)', 108, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Sale pastorizio', 204.9, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Farmaci veterinari base', 1145.16, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Mangime pollame', 1208.51, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Bancali (pallet)', 1385, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Tubi per irrigazione', 1312, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Bancali (pallet)', 351, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Compost', 8897.4, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Farmaci veterinari base', 283.78, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Fieno misto', 13524.55, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Etichette adesive', 680, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Compost', 1199.38, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Olio motore agricolo', 164.49, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Insetticida', 337.24, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Paglia di grano', 8412.03, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Mangime pollame', 1473.66, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Olio motore agricolo', 14.04, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Terriccio', 252.93, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Semi cereali', 1104.52, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Urea agricola', 64.07, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Farmaci veterinari base', 715.56, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Mangime bovini svezzamento', 418.13, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Lampade agricole', 354, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Etichette adesive', 29, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Film plastico serre', 309.18, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Integratori alimentari animali', 1296.36, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Fieno misto', 3792.16, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Bancali (pallet)', 581, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Lampade agricole', 378, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Semi cereali', 625.22, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Olio motore agricolo', 991.49, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Corda imballaggio', 824.96, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Rete antigrandine', 1209.22, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Lampade agricole', 900, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Paglia di grano', 51.38, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Semi ortaggi', 1379.7, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Compost', 11863.32, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Corda imballaggio', 625, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Mangime bovini svezzamento', 5136.31, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Gasolio agricolo', 1071.53, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Insetticida', 145.53, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Lampade agricole', 1392, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Sacchi per raccolta', 808, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Fieno misto', 798.71, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Rete antigrandine', 265.15, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Mangime pollame', 12155.67, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Lampade agricole', 866, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Insetticida', 607.81, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Corda imballaggio', 1084.66, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Tubi per irrigazione', 616, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Urea agricola', 845.86, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Vasetti vetro', 331, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Urea agricola', 162.67, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Tappi vasetti', 613, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Semi ortaggi', 630.27, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Insetticida', 1184.16, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Etichette adesive', 1124, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Tubi per irrigazione', 601, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Rete antigrandine', 978, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Gasolio agricolo', 133.25, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Compost', 2641.08, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Semi ortaggi', 439.06, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Semi foraggio', 232.25, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Bancali (pallet)', 640, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Semi cereali', 843.37, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Mangime bovini svezzamento', 769.57, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Sale pastorizio', 902.45, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Mangime bovini svezzamento', 73.25, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Tappi vasetti', 1, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Gasolio agricolo', 1124.72, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Cassette legno', 787, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Farmaci veterinari base', 1306.14, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Semi foraggio', 131.25, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Insetticida', 759.67, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Terriccio', 664.34, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Paglia di grano', 7572.54, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Semi ortaggi', 585.43, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Corda imballaggio', 603.85, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Gasolio agricolo', 1025.72, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Corda imballaggio', 1227.01, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Erbicida diserbante', 741.44, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Semi cereali', 898.71, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Sale pastorizio', 311.51, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Urea agricola', 5.97, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Insetticida', 1250.31, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Insetticida', 250.65, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Cassette plastica', 1237, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Fieno erba medica', 4253.21, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Mangime bovini svezzamento', 7332.24, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Acqua', 309.55, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Semi cereali', 302.95, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Gasolio agricolo', 1310.22, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Sacchi per raccolta', 813, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Gasolio agricolo', 246.87, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Vasetti vetro', 1113, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Erbicida diserbante', 861.24, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Lampade agricole', 1056, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Film plastico serre', 1070.01, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Corda imballaggio', 1085.76, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Tappi vasetti', 588, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Semi ortaggi', 182.07, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Mangime bovini svezzamento', 9305.41, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Gasolio agricolo', 1150.44, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Tappi vasetti', 474, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Sacchi per raccolta', 736, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Lampade agricole', 705, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Acqua', 1223.61, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Compost', 8593.13, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Vasetti vetro', 248, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Tappi vasetti', 276, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Semi foraggio', 242.17, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Cassette legno', 689, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Fertilizzante', 32.69, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Semi foraggio', 1142.49, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Integratori alimentari animali', 1133.07, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Mangime bovini svezzamento', 13271.36, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Tappi vasetti', 1238, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Vasetti vetro', 823, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Fieno erba medica', 2415.4, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Gasolio agricolo', 1027.27, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Acqua', 718.64, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Compost', 6038.45, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Olio motore agricolo', 645.54, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Semi ortaggi', 174.09, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (5, 'Cassette plastica', 302, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Semi cereali', 930.5, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Corda imballaggio', 769, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Tubi per irrigazione', 1036, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Semi ortaggi', 738.07, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Sale pastorizio', 392.27, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Lampade agricole', 762, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Cassette legno', 592, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Fieno misto', 5082.12, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Compost', 8783.96, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Farmaci veterinari base', 646.87, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Mangime pollame', 357.54, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Film plastico serre', 1098.17, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Semi cereali', 1372.48, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Mangime pollame', 9470.76, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Compost', 6792.97, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Sacchi per raccolta', 1389, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Sale pastorizio', 47.05, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Compost', 1084.29, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Tappi vasetti', 30, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Farmaci veterinari base', 1302.55, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Urea agricola', 1116.78, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Corda imballaggio', 594, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Acqua', 1121.23, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Tubi per irrigazione', 1173, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Gasolio agricolo', 188.26, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Sale pastorizio', 556.97, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Bancali (pallet)', 358, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Insetticida', 440.74, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Rete antigrandine', 545.89, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Film plastico serre', 298.39, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Mangime bovini svezzamento', 4775.17, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Semi cereali', 131.11, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Cassette legno', 804, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'tipo_risorsa', 919.57, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Cassette legno', 609, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Disinfettante stalle', 1211.14, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Correttori di pH', 1101.59, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (4, 'Mangime bovini ingrasso', 2868.03, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Gasolio agricolo', 990.46, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Fieno erba medica', 12610.86, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Sacchi per raccolta', 1218, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Compost', 831.47, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Sacchi per raccolta', 1290, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Insetticida', 569.91, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Semi foraggio', 913.98, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Fieno erba medica', 4392.31, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Mangime bovini svezzamento', 10372.03, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Corda imballaggio', 710.67, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (1, 'Cassette plastica', 1103, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Disinfettante stalle', 21.35, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Sale pastorizio', 1068.0, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Fieno misto', 4935.09, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (18, 'Film plastico serre', 409, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Cassette legno', 922, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (3, 'Gasolio agricolo', 1124.17, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Mangime pollame', 11490.35, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Terriccio', 1081.88, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Tubi per irrigazione', 623, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Corda imballaggio', 1179.51, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Tubi per irrigazione', 1223, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Integratori alimentari animali', 110.25, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Erbicida diserbante', 1063.95, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Mangime pollame', 4512.79, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (17, 'Paglia di grano', 5153.03, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Disinfettante stalle', 840.0, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Mangime bovini ingrasso', 1048.26, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Bancali (pallet)', 848, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Cassette legno', 1217, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Disinfettante stalle', 303.89, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (19, 'Cassette legno', 1234, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (2, 'Paglia di grano', 8495.3, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (6, 'Insetticida', 968.85, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Semi ortaggi', 812.22, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Rete antigrandine', 1171.2, 'mq');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Sale pastorizio', 774.31, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (15, 'Fertilizzante', 207.13, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (20, 'Terriccio', 867.45, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Terriccio', 328.67, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (13, 'Fieno erba medica', 8203.06, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Integratori alimentari animali', 367.98, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (12, 'Acqua', 1093.91, 'L');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (14, 'Tubi per irrigazione', 837.45, 'm');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Mangime pollame', 13612.82, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (9, 'Paglia di grano', 1276.09, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (10, 'Compost', 1304.29, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (11, 'Tappi vasetti', 335, 'Pezzi');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (7, 'Urea agricola', 1019.7, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (8, 'Fieno misto', 1103.54, 'Kg');
INSERT IGNORE INTO inventario_risorsa (id_produttore, tipo_risorsa, quantita_disponibile, unita_misura) values (16, 'Lampade agricole', 527, 'Pezzi');