insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (1, 'Tara', 'Morey', 'Mitchell, Pfeffer and Littel', 'tmorey0@plala.or.jp', '+30 616 617 8452');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (2, 'Rhody', 'Joutapavicius', null, 'rjoutapavicius1@is.gd', '+86 105 168 2284');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (3, 'Lesya', 'Stuckley', 'Huel, Bartoletti and Von', 'lstuckley2@devhub.com', '+7 440 903 0342');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (4, 'Richmond', 'Koschke', 'McLaughlin, Sauer and Jacobs', 'rkoschke3@ft.com', '+60 181 237 3838');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (5, 'Clayborne', 'Lainton', 'Harvey, Grimes and Boehm', 'clainton4@imgur.com', '+60 583 406 5290');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (6, 'Si', 'Tinwell', 'Bogisich, Kutch and Hauck', 'stinwell5@utexas.edu', '+57 624 778 8448');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (7, 'Lenard', 'Warboys', 'Runolfsdottir, Huels and Bode', 'lwarboys6@wufoo.com', null);
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (8, 'Mack', 'Bastow', 'Murphy-Hilpert', 'mbastow7@gmpg.org', '+86 695 877 0754');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (9, 'Lew', 'Rolstone', 'Kilback Group', 'lrolstone8@webs.com', '+98 492 514 7198');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (10, 'Allan', 'Burnand', 'Little LLC', 'aburnand9@surveymonkey.com', '+212 338 674 5205');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (11, 'Bone', 'Akehurst', 'Hyatt-Schamberger', 'bakehursta@youku.com', '+46 496 903 1338');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (12, 'Jordon', 'Luciano', 'Kunze, White and Hoeger', 'jlucianob@sakura.ne.jp', '+351 535 854 1996');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (13, 'Raine', 'Leport', 'Miller-Torp', 'rleportc@digg.com', '+351 135 994 9959');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (14, 'Benji', 'Farran', 'Brown and Sons', 'bfarrand@gravatar.com', '+86 549 673 1355');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (15, 'Cherlyn', 'Pontin', null, 'cpontine@blinklist.com', '+86 479 374 9475');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (16, 'Gene', 'Oiseau', 'Padberg LLC', 'goiseauf@google.com.hk', '+95 213 398 7178');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (17, 'Jedd', 'Coard', 'Tillman, Wunsch and Walter', 'jcoardg@yelp.com', '+223 623 634 2275');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (18, 'Tiphanie', 'Caselick', 'Green, Skiles and MacGyver', 'tcaselickh@tripod.com', null);
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (19, 'Aubrey', 'Durant', 'Ruecker LLC', 'aduranti@comcast.net', '+260 312 328 8685');
insert into produttore (id_produttore, nome, cognome, nome_azienda, indirizzo_email, numero_telefono) values (20, 'Nani', 'Benoi', 'Abernathy LLC', 'nbenoij@cyberchimps.com', '+81 956 933 9733');
