insert into prodotto (id_prodotto, nome) values (1, 'Latte crudo');
insert into prodotto (id_prodotto, nome) values (2, 'Latte pastorizzato');
insert into prodotto (id_prodotto, nome) values (3, 'Latte fermentato');
insert into prodotto (id_prodotto, nome) values (4, 'Latte senza lattosio');
insert into prodotto (id_prodotto, nome) values (5, 'Burro');
insert into prodotto (id_prodotto, nome) values (6, 'Burro chiarificato');
insert into prodotto (id_prodotto, nome) values (7, 'Panna fresca');
insert into prodotto (id_prodotto, nome) values (8, 'Panna da cucina');
insert into prodotto (id_prodotto, nome) values (9, 'Yogurt bianco');
insert into prodotto (id_prodotto, nome) values (10, 'Yogurt alla frutta');
insert into prodotto (id_prodotto, nome) values (11, 'Yogurt con miele');
insert into prodotto (id_prodotto, nome) values (12, 'Yogurt con cereali');
insert into prodotto (id_prodotto, nome) values (13, 'Yogurt alla vaniglia');
insert into prodotto (id_prodotto, nome) values (14, 'Yogurt al cacao');
insert into prodotto (id_prodotto, nome) values (15, 'Yogurt greco');
insert into prodotto (id_prodotto, nome) values (16, 'Ricotta fresca');
insert into prodotto (id_prodotto, nome) values (17, 'Ricotta stagionata');
insert into prodotto (id_prodotto, nome) values (18, 'Ricotta con miele');
insert into prodotto (id_prodotto, nome) values (19, 'Ricotta con cacao');
insert into prodotto (id_prodotto, nome) values (20, 'Mozzarella');
insert into prodotto (id_prodotto, nome) values (21, 'Mozzarella affumicata');
insert into prodotto (id_prodotto, nome) values (22, 'Formaggio fresco');
insert into prodotto (id_prodotto, nome) values (23, 'Formaggio stagionato');
insert into prodotto (id_prodotto, nome) values (24, 'Formaggio semistagionato');
insert into prodotto (id_prodotto, nome) values (25, 'Formaggio erborinato');
insert into prodotto (id_prodotto, nome) values (26, 'Formaggio a pasta filata');
insert into prodotto (id_prodotto, nome) values (27, 'Formaggio alle erbe aromatiche');
insert into prodotto (id_prodotto, nome) values (28, 'Formaggio agli agrumi');
insert into prodotto (id_prodotto, nome) values (29, 'Formaggio al pepe');
insert into prodotto (id_prodotto, nome) values (30, 'Formaggio al tartufo');
insert into prodotto (id_prodotto, nome) values (31, 'Formaggio al miele');
insert into prodotto (id_prodotto, nome) values (32, 'Formaggio alle noci');
insert into prodotto (id_prodotto, nome) values (33, 'Formaggio alle olive');
insert into prodotto (id_prodotto, nome) values (34, 'Formaggio spalmabile');
insert into prodotto (id_prodotto, nome) values (35, 'Formaggio caprino');
insert into prodotto (id_prodotto, nome) values (36, 'Formaggio ovino');
insert into prodotto (id_prodotto, nome) values (37, 'Parmigiano');
insert into prodotto (id_prodotto, nome) values (38, 'Pecorino');
insert into prodotto (id_prodotto, nome) values (39, 'Caciotta');
insert into prodotto (id_prodotto, nome) values (40, 'Provola');
insert into prodotto (id_prodotto, nome) values (41, 'Provolone');
insert into prodotto (id_prodotto, nome) values (42, 'Scamorza');
insert into prodotto (id_prodotto, nome) values (43, 'Uova fresche');
insert into prodotto (id_prodotto, nome) values (44, 'Uova pastorizzate');
insert into prodotto (id_prodotto, nome) values (45, 'Albume');
insert into prodotto (id_prodotto, nome) values (46, 'Tuorlo');
insert into prodotto (id_prodotto, nome) values (47, 'Carne bovina');
insert into prodotto (id_prodotto, nome) values (48, 'Carne suina');
insert into prodotto (id_prodotto, nome) values (49, 'Carne ovina');
insert into prodotto (id_prodotto, nome) values (50, 'Carne caprina');
insert into prodotto (id_prodotto, nome) values (51, 'Carne avicola');
insert into prodotto (id_prodotto, nome) values (52, 'Carne macinata');
insert into prodotto (id_prodotto, nome) values (53, 'Carne lavorata');
insert into prodotto (id_prodotto, nome) values (54, 'Carne marinata agli agrumi');
insert into prodotto (id_prodotto, nome) values (55, 'Carne con erbe aromatiche');
insert into prodotto (id_prodotto, nome) values (56, 'Carne speziata al pepe');
insert into prodotto (id_prodotto, nome) values (57, 'Salsiccia');
insert into prodotto (id_prodotto, nome) values (58, 'Salsiccia al vino rosso');
insert into prodotto (id_prodotto, nome) values (59, 'Salame');
insert into prodotto (id_prodotto, nome) values (60, 'Salame al vino rosso');
insert into prodotto (id_prodotto, nome) values (61, 'Prosciutto crudo');
insert into prodotto (id_prodotto, nome) values (62, 'Prosciutto cotto');
insert into prodotto (id_prodotto, nome) values (63, 'Pancetta');
insert into prodotto (id_prodotto, nome) values (64, 'Speck');
insert into prodotto (id_prodotto, nome) values (65, 'Bresaola');
insert into prodotto (id_prodotto, nome) values (66, 'Lardo');
insert into prodotto (id_prodotto, nome) values (67, 'Carne essiccata');
insert into prodotto (id_prodotto, nome) values (68, 'Hamburger');
insert into prodotto (id_prodotto, nome) values (69, 'Hamburger con spezie');
insert into prodotto (id_prodotto, nome) values (70, 'Hamburger con erbe aromatiche');
insert into prodotto (id_prodotto, nome) values (71, 'Polpette');
insert into prodotto (id_prodotto, nome) values (72, 'Polpette con spezie');
insert into prodotto (id_prodotto, nome) values (73, 'Polpette con verdure');
insert into prodotto (id_prodotto, nome) values (74, 'Brodo di carne');
insert into prodotto (id_prodotto, nome) values (75, 'Brodo con erbe aromatiche');
insert into prodotto (id_prodotto, nome) values (76, 'Gelatina animale');
insert into prodotto (id_prodotto, nome) values (77, 'Miele');
insert into prodotto (id_prodotto, nome) values (78, 'Miele di agrumi');
insert into prodotto (id_prodotto, nome) values (79, 'Miele di acacia');
insert into prodotto (id_prodotto, nome) values (80, 'Cera d’api');
insert into prodotto (id_prodotto, nome) values (81, 'Latte in polvere');
insert into prodotto (id_prodotto, nome) values (82, 'Siero di latte');
insert into prodotto (id_prodotto, nome) values (83, 'Formaggio fuso');
insert into prodotto (id_prodotto, nome) values (84, 'Crema di formaggio alle erbe');
insert into prodotto (id_prodotto, nome) values (85, 'Crema di formaggio al peperoncino');
insert into prodotto (id_prodotto, nome) values (86, 'Dessert a base latte');
insert into prodotto (id_prodotto, nome) values (87, 'Dessert latte e frutta');
insert into prodotto (id_prodotto, nome) values (88, 'Dessert latte e cereali');
insert into prodotto (id_prodotto, nome) values (89, 'Gelato artigianale');
insert into prodotto (id_prodotto, nome) values (90, 'Gelato al latte');
insert into prodotto (id_prodotto, nome) values (91, 'Gelato alla frutta');
insert into prodotto (id_prodotto, nome) values (92, 'Gelato al miele');
insert into prodotto (id_prodotto, nome) values (93, 'Kefir');
insert into prodotto (id_prodotto, nome) values (94, 'Latte al cacao');
insert into prodotto (id_prodotto, nome) values (95, 'Latte alla vaniglia');
insert into prodotto (id_prodotto, nome) values (96, 'Latte al miele');
insert into prodotto (id_prodotto, nome) values (97, 'Bevanda a base latte');
insert into prodotto (id_prodotto, nome) values (98, 'Proteine del latte');
insert into prodotto (id_prodotto, nome) values (99, 'Grano');
insert into prodotto (id_prodotto, nome) values (100, 'Mais');
insert into prodotto (id_prodotto, nome) values (101, 'Orzo');
insert into prodotto (id_prodotto, nome) values (102, 'Riso');
insert into prodotto (id_prodotto, nome) values (103, 'Farina');
insert into prodotto (id_prodotto, nome) values (104, 'Farina integrale');
insert into prodotto (id_prodotto, nome) values (105, 'Farina di mais');
insert into prodotto (id_prodotto, nome) values (106, 'Semola');
insert into prodotto (id_prodotto, nome) values (107, 'Pane');
insert into prodotto (id_prodotto, nome) values (108, 'Pane con semi');
insert into prodotto (id_prodotto, nome) values (109, 'Pane alle erbe aromatiche');
insert into prodotto (id_prodotto, nome) values (110, 'Pasta');
insert into prodotto (id_prodotto, nome) values (111, 'Pasta fresca');
insert into prodotto (id_prodotto, nome) values (112, 'Pasta secca');
insert into prodotto (id_prodotto, nome) values (113, 'Pasta al pomodoro');
insert into prodotto (id_prodotto, nome) values (114, 'Pasta agli spinaci');
insert into prodotto (id_prodotto, nome) values (115, 'Pasta ripiena vegetale');
insert into prodotto (id_prodotto, nome) values (116, 'Biscotti');
insert into prodotto (id_prodotto, nome) values (117, 'Biscotti con frutta');
insert into prodotto (id_prodotto, nome) values (118, 'Dolci da forno');
insert into prodotto (id_prodotto, nome) values (119, 'Dolci con frutta');
insert into prodotto (id_prodotto, nome) values (120, 'Olio vegetale');
insert into prodotto (id_prodotto, nome) values (121, 'Olio extravergine');
insert into prodotto (id_prodotto, nome) values (122, 'Olio con erbe aromatiche');
insert into prodotto (id_prodotto, nome) values (123, 'Olio al peperoncino');
insert into prodotto (id_prodotto, nome) values (124, 'Vino rosso');
insert into prodotto (id_prodotto, nome) values (125, 'Vino bianco');
insert into prodotto (id_prodotto, nome) values (126, 'Vino rosato');
insert into prodotto (id_prodotto, nome) values (127, 'Vino con spezie');
insert into prodotto (id_prodotto, nome) values (128, 'Succo di frutta');
insert into prodotto (id_prodotto, nome) values (129, 'Succo di agrumi');
insert into prodotto (id_prodotto, nome) values (130, 'Nettare di frutta');
insert into prodotto (id_prodotto, nome) values (131, 'Confettura');
insert into prodotto (id_prodotto, nome) values (132, 'Confettura con spezie');
insert into prodotto (id_prodotto, nome) values (133, 'Marmellata di agrumi');
insert into prodotto (id_prodotto, nome) values (134, 'Marmellata con spezie');
insert into prodotto (id_prodotto, nome) values (135, 'Conserva di pomodoro');
insert into prodotto (id_prodotto, nome) values (136, 'Passata di pomodoro');
insert into prodotto (id_prodotto, nome) values (137, 'Salsa vegetale');
insert into prodotto (id_prodotto, nome) values (138, 'Salsa piccante');
insert into prodotto (id_prodotto, nome) values (139, 'Verdure fresche');
insert into prodotto (id_prodotto, nome) values (140, 'Verdure surgelate');
insert into prodotto (id_prodotto, nome) values (141, 'Verdure grigliate');
insert into prodotto (id_prodotto, nome) values (142, 'Verdure sott’olio');
insert into prodotto (id_prodotto, nome) values (143, 'Verdure sott’aceto');
insert into prodotto (id_prodotto, nome) values (144, 'Verdure marinate');
insert into prodotto (id_prodotto, nome) values (145, 'Verdure fermentate');
insert into prodotto (id_prodotto, nome) values (146, 'Insalata mista');
insert into prodotto (id_prodotto, nome) values (147, 'Insalata pronta con condimento');
insert into prodotto (id_prodotto, nome) values (148, 'Pomodori');
insert into prodotto (id_prodotto, nome) values (149, 'Zucchine');
insert into prodotto (id_prodotto, nome) values (150, 'Melanzane');
insert into prodotto (id_prodotto, nome) values (151, 'Peperoni');
insert into prodotto (id_prodotto, nome) values (152, 'Patate');
insert into prodotto (id_prodotto, nome) values (153, 'Cipolle');
insert into prodotto (id_prodotto, nome) values (154, 'Aglio');
insert into prodotto (id_prodotto, nome) values (155, 'Carote');
insert into prodotto (id_prodotto, nome) values (156, 'Lattuga');
insert into prodotto (id_prodotto, nome) values (157, 'Radicchio');
insert into prodotto (id_prodotto, nome) values (158, 'Frutta fresca');
insert into prodotto (id_prodotto, nome) values (159, 'Frutta secca');
insert into prodotto (id_prodotto, nome) values (160, 'Frutta essiccata');
insert into prodotto (id_prodotto, nome) values (161, 'Frutta sciroppata');
insert into prodotto (id_prodotto, nome) values (162, 'Frutta caramellata');
insert into prodotto (id_prodotto, nome) values (163, 'Frutta macedonia pronta');
insert into prodotto (id_prodotto, nome) values (164, 'Mele');
insert into prodotto (id_prodotto, nome) values (165, 'Pere');
insert into prodotto (id_prodotto, nome) values (166, 'Pesche');
insert into prodotto (id_prodotto, nome) values (167, 'Ciliegie');
insert into prodotto (id_prodotto, nome) values (168, 'Fragole');
insert into prodotto (id_prodotto, nome) values (169, 'Agrumi');
insert into prodotto (id_prodotto, nome) values (170, 'Mandorle');
insert into prodotto (id_prodotto, nome) values (171, 'Noci');
insert into prodotto (id_prodotto, nome) values (172, 'Nocciole');
insert into prodotto (id_prodotto, nome) values (173, 'Cereali tostati');
insert into prodotto (id_prodotto, nome) values (174, 'Snack di frutta');
insert into prodotto (id_prodotto, nome) values (175, 'Snack vegetali');
insert into prodotto (id_prodotto, nome) values (176, 'Purea di frutta');
insert into prodotto (id_prodotto, nome) values (177, 'Purea di verdura');
insert into prodotto (id_prodotto, nome) values (178, 'Concentrato vegetale');
insert into prodotto (id_prodotto, nome) values (179, 'Succo concentrato');
insert into prodotto (id_prodotto, nome) values (180, 'Bevanda a base cereali');
