insert into risorsa (tipo_risorsa) values ('Semi ortaggi');
insert into risorsa (tipo_risorsa) values ('Semi cereali');
insert into risorsa (tipo_risorsa) values ('Semi foraggio');
insert into risorsa (tipo_risorsa) values ('Sacchi per raccolta');
insert into risorsa (tipo_risorsa) values ('Bancali (pallet)');
insert into risorsa (tipo_risorsa) values ('Lampade agricole');
insert into risorsa (tipo_risorsa) values ('Farmaci veterinari base');
insert into risorsa (tipo_risorsa) values ('Integratori alimentari animali');
insert into risorsa (tipo_risorsa) values ('Correttori di pH');
insert into risorsa (tipo_risorsa) values ('Acqua');
insert into risorsa (tipo_risorsa) values ('Mangime bovini svezzamento');
insert into risorsa (tipo_risorsa) values ('Mangime bovini ingrasso');
insert into risorsa (tipo_risorsa) values ('Mangime pollame');
insert into risorsa (tipo_risorsa) values ('Fieno erba medica');
insert into risorsa (tipo_risorsa) values ('Fieno misto');
insert into risorsa (tipo_risorsa) values ('Paglia di grano');
insert into risorsa (tipo_risorsa) values ('Fertilizzante');
insert into risorsa (tipo_risorsa) values ('Urea agricola');
insert into risorsa (tipo_risorsa) values ('Compost');
insert into risorsa (tipo_risorsa) values ('Gasolio agricolo');
insert into risorsa (tipo_risorsa) values ('Erbicida diserbante');
insert into risorsa (tipo_risorsa) values ('Insetticida');
insert into risorsa (tipo_risorsa) values ('Rete antigrandine');
insert into risorsa (tipo_risorsa) values ('Tubi per irrigazione');
insert into risorsa (tipo_risorsa) values ('Olio motore agricolo');
insert into risorsa (tipo_risorsa) values ('Corda imballaggio');
insert into risorsa (tipo_risorsa) values ('Cassette plastica');
insert into risorsa (tipo_risorsa) values ('Cassette legno');
insert into risorsa (tipo_risorsa) values ('Etichette adesive');
insert into risorsa (tipo_risorsa) values ('Vasetti vetro');
insert into risorsa (tipo_risorsa) values ('Tappi vasetti');
insert into risorsa (tipo_risorsa) values ('Disinfettante stalle');
insert into risorsa (tipo_risorsa) values ('Sale pastorizio');
insert into risorsa (tipo_risorsa) values ('Film plastico serre');
insert into risorsa (tipo_risorsa) values ('Terriccio');
