insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (1, 'Sensore clima campo aperto', '2023-02-25', 7);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (2, 'Sensore fertilità suolo', '2024-06-14', 67);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (3, 'Sensore clima campo aperto', '2024-05-13', 12);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (4, 'Sensore umidità suolo', '2023-03-23', 170);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (5, 'Sensore fertilità suolo', '2026-01-13', 163);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (6, 'Sensore velocità vento', '2025-03-30', 35);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (7, 'Sensore temperatura aria', '2025-06-07', 59);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (8, 'Sensore temperatura suolo', '2025-10-01', 139);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (9, 'Sensore monitoraggio colture', '2025-02-14', 47);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (10, 'Stazione meteo agricola', '2024-05-06', 67);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (11, 'Sensore temperatura aria', '2026-01-03', 63);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (12, 'Sensore precipitazioni', '2026-01-12', 226);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (13, 'Sensore umidità suolo', '2024-01-21', 28);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (14, 'Sensore temperatura aria', '2024-03-26', 61);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (15, 'Sensore umidità suolo', '2024-04-06', 37);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (16, 'Sensore monitoraggio serra', '2024-05-23', 29);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (17, 'Sensore precipitazioni', '2025-08-13', 118);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (18, 'Sensore analisi atmosferica', '2026-04-04', 86);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (19, 'Sensore monitoraggio serra', '2023-07-23', 220);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (20, 'Sensore clima campo aperto', '2025-09-29', 86);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (21, 'Sensore temperatura suolo', '2023-05-31', 213);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (22, 'Sensore analisi atmosferica', '2023-03-24', 81);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (23, 'Sensore pH suolo', '2023-11-03', 261);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (24, 'Sensore temperatura suolo', '2025-02-04', 279);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (25, 'Stazione meteo agricola', '2023-08-28', 60);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (26, 'Sensore irrigazione automatica', '2025-05-11', 134);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (27, 'Sensore monitoraggio suolo', '2024-03-14', 160);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (28, 'Sensore monitoraggio serra', '2024-03-03', 175);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (29, 'Sensore temperatura suolo', '2023-01-25', 119);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (30, 'Sensore pH suolo', '2025-08-17', 106);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (31, 'Sensore temperatura suolo', '2025-10-17', 62);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (32, 'Sensore monitoraggio suolo', '2023-09-23', 122);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (33, 'Sensore monitoraggio serra', '2025-01-15', 121);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (34, 'Sensore temperatura aria', '2023-08-16', 63);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (35, 'Sensore monitoraggio suolo', '2025-11-17', 106);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (36, 'Sensore temperatura aria', '2023-06-11', 230);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (37, 'Sensore analisi atmosferica', '2023-01-19', 37);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (38, 'Sensore irrigazione automatica', '2025-06-06', 228);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (39, 'Stazione meteo agricola', '2024-01-20', 24);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (40, 'Sensore umidità aria', '2025-03-04', 71);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (41, 'Sensore precipitazioni', '2025-01-09', 61);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (42, 'Sensore clima campo aperto', '2024-05-17', 197);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (43, 'Sensore monitoraggio serra', '2024-06-26', 39);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (44, 'Sensore pH suolo', '2024-01-10', 46);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (45, 'Sensore irrigazione automatica', '2024-02-08', 123);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (46, 'Sensore clima campo aperto', '2024-07-19', 160);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (47, 'Sensore pH suolo', '2026-01-27', 60);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (48, 'Sensore monitoraggio serra', '2023-01-07', 228);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (49, 'Sensore umidità suolo', '2025-01-27', 164);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (50, 'Sensore ambiente allevamento', '2024-03-07', 191);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (51, 'Sensore precipitazioni', '2025-10-22', 228);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (52, 'Sensore livello CO2', '2023-10-20', 73);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (53, 'Sensore microclima serra', '2024-02-23', 47);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (54, 'Sensore umidità aria', '2026-02-18', 121);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (55, 'Sensore ambiente allevamento', '2026-04-16', 63);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (56, 'Sensore analisi atmosferica', '2023-09-06', 46);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (57, 'Sensore clima campo aperto', '2024-09-19', 88);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (58, 'Sensore monitoraggio colture', '2025-01-10', 290);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (59, 'Sensore velocità vento', '2026-01-20', 236);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (60, 'Sensore umidità suolo', '2023-05-18', 220);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (61, 'Sensore monitoraggio serra', '2023-02-14', 247);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (62, 'Sensore temperatura aria', '2024-02-20', 122);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (63, 'Stazione meteo agricola', '2023-02-03', 5);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (64, 'Sensore controllo irrigazione', '2023-01-23', 163);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (65, 'Sensore microclima serra', '2023-08-21', 147);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (66, 'Sensore umidità aria', '2024-09-14', 170);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (67, 'Sensore pH suolo', '2024-06-29', 108);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (68, 'Sensore pH suolo', '2025-02-06', 5);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (69, 'Sensore umidità aria', '2024-12-27', 42);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (70, 'Sensore umidità suolo', '2023-05-24', 35);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (71, 'Sensore precipitazioni', '2023-10-31', 118);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (72, 'Sensore ambiente allevamento', '2025-01-11', 134);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (73, 'Sensore analisi atmosferica', '2024-01-08', 103);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (74, 'Sensore monitoraggio suolo', '2023-06-15', 242);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (75, 'Sensore livello CO2', '2024-09-04', 255);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (76, 'Sensore irrigazione automatica', '2025-01-29', 17);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (77, 'Sensore precipitazioni', '2025-06-01', 113);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (78, 'Sensore precipitazioni', '2024-07-25', 12);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (79, 'Stazione meteo agricola', '2025-10-15', 96);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (80, 'Sensore umidità suolo', '2024-07-20', 121);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (81, 'Sensore irrigazione automatica', '2023-01-17', 37);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (82, 'Sensore precipitazioni', '2024-03-16', 61);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (83, 'Sensore umidità aria', '2026-02-10', 164);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (84, 'Stazione meteo agricola', '2026-02-03', 187);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (85, 'Sensore monitoraggio suolo', '2025-05-20', 223);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (86, 'Sensore clima campo aperto', '2024-09-22', 236);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (87, 'Sensore temperatura aria', '2025-04-05', 47);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (88, 'Sensore microclima serra', '2024-12-05', 112);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (89, 'Sensore velocità vento', '2026-04-02', 261);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (90, 'Sensore umidità suolo', '2026-03-05', 208);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (91, 'Sensore temperatura aria', '2024-04-06', 62);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (92, 'Sensore ambiente allevamento', '2023-01-16', 277);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (93, 'Sensore velocità vento', '2025-05-03', 228);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (94, 'Sensore monitoraggio serra', '2026-03-13', 159);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (95, 'Sensore monitoraggio colture', '2024-04-12', 136);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (96, 'Sensore monitoraggio colture', '2023-07-12', 51);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (97, 'Sensore umidità aria', '2025-08-11', 145);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (98, 'Sensore clima campo aperto', '2024-06-29', 48);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (99, 'Sensore monitoraggio suolo', '2025-05-08', 236);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (100, 'Sensore analisi atmosferica', '2025-01-10', 253);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (101, 'Sensore irrigazione automatica', '2024-10-13', 160);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (102, 'Sensore monitoraggio suolo', '2024-12-14', 39);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (103, 'Sensore pH suolo', '2023-08-11', 136);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (104, 'Sensore temperatura aria', '2023-12-08', 224);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (105, 'Sensore monitoraggio suolo', '2024-05-13', 20);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (106, 'Sensore monitoraggio serra', '2024-06-10', 230);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (107, 'Sensore microclima serra', '2024-07-02', 230);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (108, 'Sensore irrigazione automatica', '2024-12-07', 103);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (109, 'Sensore monitoraggio serra', '2026-04-30', 250);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (110, 'Sensore ambiente allevamento', '2025-09-16', 193);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (111, 'Sensore umidità aria', '2024-02-03', 60);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (112, 'Sensore analisi atmosferica', '2025-12-02', 250);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (113, 'Sensore clima campo aperto', '2023-11-17', 185);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (114, 'Sensore analisi atmosferica', '2025-04-04', 165);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (115, 'Sensore clima campo aperto', '2023-02-15', 106);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (116, 'Sensore controllo irrigazione', '2026-04-01', 83);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (117, 'Sensore fertilità suolo', '2024-03-30', 137);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (118, 'Sensore umidità suolo', '2024-12-22', 103);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (119, 'Sensore velocità vento', '2024-04-15', 165);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (120, 'Sensore analisi atmosferica', '2023-03-06', 81);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (121, 'Sensore umidità suolo', '2023-04-03', 161);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (122, 'Sensore temperatura aria', '2025-10-26', 226);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (123, 'Sensore temperatura aria', '2026-03-29', 21);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (124, 'Sensore ambiente allevamento', '2024-10-24', 295);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (125, 'Sensore velocità vento', '2023-10-30', 59);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (126, 'Stazione meteo agricola', '2023-03-05', 237);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (127, 'Sensore umidità suolo', '2023-07-03', 71);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (128, 'Sensore monitoraggio serra', '2024-07-15', 7);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (129, 'Sensore temperatura aria', '2025-01-15', 236);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (130, 'Sensore temperatura aria', '2023-09-17', 73);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (131, 'Sensore precipitazioni', '2024-09-04', 106);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (132, 'Sensore ambiente allevamento', '2023-06-18', 242);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (133, 'Sensore livello CO2', '2025-01-26', 175);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (134, 'Sensore monitoraggio suolo', '2024-06-19', 24);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (135, 'Sensore fertilità suolo', '2023-05-15', 197);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (136, 'Sensore controllo irrigazione', '2023-12-28', 183);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (137, 'Sensore temperatura suolo', '2023-05-26', 48);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (138, 'Sensore monitoraggio colture', '2023-04-01', 19);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (139, 'Sensore umidità aria', '2024-12-21', 35);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (140, 'Stazione meteo agricola', '2023-09-26', 165);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (141, 'Sensore monitoraggio colture', '2023-03-10', 96);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (142, 'Sensore umidità suolo', '2025-12-17', 231);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (143, 'Sensore monitoraggio serra', '2025-09-25', 282);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (144, 'Sensore fertilità suolo', '2024-03-19', 290);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (145, 'Sensore clima campo aperto', '2025-11-05', 213);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (146, 'Sensore precipitazioni', '2025-12-17', 179);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (147, 'Sensore umidità suolo', '2023-06-27', 47);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (148, 'Sensore livello CO2', '2024-11-12', 134);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (149, 'Sensore irrigazione automatica', '2024-08-31', 35);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (150, 'Sensore fertilità suolo', '2023-02-24', 86);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (151, 'Sensore umidità suolo', '2023-11-03', 208);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (152, 'Sensore monitoraggio suolo', '2023-12-05', 175);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (153, 'Sensore microclima serra', '2024-03-12', 186);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (154, 'Sensore umidità suolo', '2023-01-11', 191);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (155, 'Sensore monitoraggio colture', '2024-03-05', 150);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (156, 'Sensore microclima serra', '2025-03-18', 136);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (157, 'Sensore velocità vento', '2023-09-13', 220);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (158, 'Sensore monitoraggio suolo', '2026-04-24', 261);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (159, 'Sensore monitoraggio serra', '2024-06-13', 217);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (160, 'Sensore controllo irrigazione', '2024-01-22', 230);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (161, 'Sensore velocità vento', '2024-09-10', 38);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (162, 'Sensore temperatura suolo', '2026-03-13', 112);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (163, 'Sensore pH suolo', '2023-02-26', 71);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (164, 'Sensore velocità vento', '2024-04-18', 170);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (165, 'Sensore monitoraggio suolo', '2024-07-14', 165);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (166, 'Sensore monitoraggio colture', '2025-10-11', 42);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (167, 'Sensore monitoraggio suolo', '2023-05-31', 237);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (168, 'Sensore precipitazioni', '2026-03-25', 96);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (169, 'Sensore microclima serra', '2023-05-15', 150);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (170, 'Sensore monitoraggio colture', '2025-01-11', 112);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (171, 'Sensore livello CO2', '2025-09-23', 55);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (172, 'Sensore controllo irrigazione', '2023-02-25', 44);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (173, 'Sensore monitoraggio colture', '2025-05-06', 220);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (174, 'Sensore monitoraggio serra', '2023-09-20', 112);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (175, 'Sensore clima campo aperto', '2026-04-09', 208);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (176, 'Sensore clima campo aperto', '2025-10-31', 5);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (177, 'Sensore monitoraggio serra', '2025-10-17', 236);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (178, 'Sensore pH suolo', '2024-02-27', 153);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (179, 'Sensore clima campo aperto', '2025-08-17', 253);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (180, 'Sensore clima campo aperto', '2024-10-30', 86);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (181, 'Sensore temperatura aria', '2023-12-24', 165);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (182, 'Sensore controllo irrigazione', '2023-04-24', 133);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (183, 'Sensore microclima serra', '2024-11-21', 160);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (184, 'Stazione meteo agricola', '2023-02-16', 234);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (185, 'Sensore pH suolo', '2023-09-23', 147);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (186, 'Sensore temperatura aria', '2023-07-03', 63);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (187, 'Sensore pH suolo', '2026-03-25', 231);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (188, 'Sensore temperatura suolo', '2025-05-21', 87);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (189, 'Sensore umidità suolo', '2025-10-23', 143);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (190, 'Sensore temperatura suolo', '2024-02-22', 83);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (191, 'Sensore fertilità suolo', '2024-04-10', 71);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (192, 'Sensore livello CO2', '2023-07-31', 231);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (193, 'Sensore microclima serra', '2024-02-19', 83);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (194, 'Sensore fertilità suolo', '2023-01-03', 175);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (195, 'Sensore livello CO2', '2024-12-02', 290);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (196, 'Sensore ambiente allevamento', '2026-01-02', 47);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (197, 'Sensore clima campo aperto', '2025-11-19', 191);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (198, 'Stazione meteo agricola', '2025-02-08', 97);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (199, 'Sensore irrigazione automatica', '2023-05-22', 108);
insert into sensore (id_sensore, tipo_sensore, data_installazione, id_attivita) values (200, 'Sensore controllo irrigazione', '2023-02-08', 106);
